-- Migration: 010_create_sent_emails.sql
-- Description: Creates sent_emails table for tracking email delivery logs and failures.

CREATE TABLE IF NOT EXISTS public.sent_emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'sent',
  error_message TEXT,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.sent_emails ENABLE ROW LEVEL SECURITY;

-- Policies for sent_emails
DROP POLICY IF EXISTS "Allow public select on sent_emails" ON public.sent_emails;
CREATE POLICY "Allow public select on sent_emails"
  ON public.sent_emails FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Allow public insert on sent_emails" ON public.sent_emails;
CREATE POLICY "Allow public insert on sent_emails"
  ON public.sent_emails FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete on sent_emails" ON public.sent_emails;
CREATE POLICY "Allow public delete on sent_emails"
  ON public.sent_emails FOR DELETE
  USING (true);

-- ⚠️ ACTION REQUIRED: Jalankan SQL di bawah ini di Supabase SQL Editor jika tabel sent_emails belum ada:
/*
CREATE TABLE IF NOT EXISTS public.sent_emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'sent',
  error_message TEXT,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sent_emails ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on sent_emails" ON public.sent_emails FOR SELECT USING (true);
CREATE POLICY "Allow public insert on sent_emails" ON public.sent_emails FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete on sent_emails" ON public.sent_emails FOR DELETE USING (true);
*/
